// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY21SlFxfbIxjej-Egawbk9ZPSoN7TzEk',
    appId: '1:832994573743:web:659df8334090db2fd9c35a',
    messagingSenderId: '832994573743',
    projectId: 'barberstyle-a141a',
    authDomain: 'barberstyle-a141a.firebaseapp.com',
    storageBucket: 'barberstyle-a141a.firebasestorage.app',
    measurementId: 'G-DCS25P6QKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzH48dUEwLEPyfV1u0YU4VyDPx4jh6h_8',
    appId: '1:832994573743:android:73a22dd8df4537b6d9c35a',
    messagingSenderId: '832994573743',
    projectId: 'barberstyle-a141a',
    storageBucket: 'barberstyle-a141a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBETXmAra09ICDf4YLdlnRkgIooGrgCgdI',
    appId: '1:832994573743:ios:8a085b655e850a25d9c35a',
    messagingSenderId: '832994573743',
    projectId: 'barberstyle-a141a',
    storageBucket: 'barberstyle-a141a.firebasestorage.app',
    iosBundleId: 'com.example.barberstyle',
  );
}
